# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mongork < Formula
  desc "MongoDB migration tool with MCP support"
  homepage "https://github.com/drewjocham/mongork"
  version "0.0.3-beta.5"
  license "MIT"

  depends_on "mongodb/brew/mongodb-community" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.3-beta.5/mongork_Darwin_x86_64.tar.gz"
      sha256 "879524c43e34e0dc27ab58bbc486361b6919b29e63688337db9fc830d40c2c78"

      define_method(:install) do
        bin.install "mongork" => "mt"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.3-beta.5/mongork_Darwin_arm64.tar.gz"
      sha256 "eb24a5fdd9b7c8e75efdee682881f72ee9ae47e2d88fae173ad06b17b1d24278"

      define_method(:install) do
        bin.install "mongork" => "mt"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.3-beta.5/mongork_Linux_x86_64.tar.gz"
      sha256 "dbd0528870cbf532d1e764a17d71e94f73fcbb4d19a727387eda449e47916618"
      define_method(:install) do
        bin.install "mongork" => "mt"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.3-beta.5/mongork_Linux_arm64.tar.gz"
      sha256 "7fe5474421f4a6ac39cc6b60c594a103de12983778964785e1f44b9067ee02ad"
      define_method(:install) do
        bin.install "mongork" => "mt"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
  end

  test do
    system "#{bin}/mt --version"
  end
end
