# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mongork < Formula
  desc "MongoDB migration tool with MCP support"
  homepage "https://github.com/drewjocham/mongork"
  version "0.0.6-beta"
  license "MIT"

  depends_on "mongodb/brew/mongodb-community" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.6-beta/mongork_Darwin_x86_64.tar.gz"
      sha256 "71ea7e760a90dba3ef70032451ae318f516d042c68f2b9e4955dca2a44c26849"

      define_method(:install) do
        bin.install "mongork" => "mongo"
        bin.install_symlink "mongo" => "mmo"
        bin.install_symlink "mongo" => "mt"
        bin.install_symlink "mongo" => "mmt"
        bin.install_symlink "mongo" => "mongork"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.6-beta/mongork_Darwin_arm64.tar.gz"
      sha256 "330798c27d31ee164aada9e10fd4a15efa01332c29f2e1bae4900701c94a55e6"

      define_method(:install) do
        bin.install "mongork" => "mongo"
        bin.install_symlink "mongo" => "mmo"
        bin.install_symlink "mongo" => "mt"
        bin.install_symlink "mongo" => "mmt"
        bin.install_symlink "mongo" => "mongork"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.6-beta/mongork_Linux_x86_64.tar.gz"
      sha256 "e2398b9eaef2d2b092cba6341317f393a6a7d4b00845915676a1e07ec9ae3725"
      define_method(:install) do
        bin.install "mongork" => "mongo"
        bin.install_symlink "mongo" => "mmo"
        bin.install_symlink "mongo" => "mt"
        bin.install_symlink "mongo" => "mmt"
        bin.install_symlink "mongo" => "mongork"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.6-beta/mongork_Linux_arm64.tar.gz"
      sha256 "a72b8ec45b13885558529b73a8ba212aee1a4d8ee3f15cd96e7ed14fa06c6c95"
      define_method(:install) do
        bin.install "mongork" => "mongo"
        bin.install_symlink "mongo" => "mmo"
        bin.install_symlink "mongo" => "mt"
        bin.install_symlink "mongo" => "mmt"
        bin.install_symlink "mongo" => "mongork"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
  end

  test do
    system "#{bin}/mongo --version"
  end
end
