# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mongork < Formula
  desc "MongoDB migration tool with MCP support"
  homepage "https://github.com/drewjocham/mongork"
  version "0.0.3-beta.7"
  license "MIT"

  depends_on "mongodb/brew/mongodb-community" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.3-beta.7/mongork_Darwin_x86_64.tar.gz"
      sha256 "1719932f6b0abbc6db3e1f20ee4a3e7db078a5a37e08d4374c349a70981b7bd0"

      define_method(:install) do
        bin.install "mongork" => "mongo"
        bin.install_symlink "mongo" => "mmo"
        bin.install_symlink "mongo" => "mt"
        bin.install_symlink "mongo" => "mmt"
        bin.install_symlink "mongo" => "mongork"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.3-beta.7/mongork_Darwin_arm64.tar.gz"
      sha256 "cca5101f5b90df975e848c5e928a8d776f8d3a94ee6be2465cd0f7a50a77df36"

      define_method(:install) do
        bin.install "mongork" => "mongo"
        bin.install_symlink "mongo" => "mmo"
        bin.install_symlink "mongo" => "mt"
        bin.install_symlink "mongo" => "mmt"
        bin.install_symlink "mongo" => "mongork"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.3-beta.7/mongork_Linux_x86_64.tar.gz"
      sha256 "10468b3f279981611db9b93120946066afe5b52b3c6a637c68af7a2b80909381"
      define_method(:install) do
        bin.install "mongork" => "mongo"
        bin.install_symlink "mongo" => "mmo"
        bin.install_symlink "mongo" => "mt"
        bin.install_symlink "mongo" => "mmt"
        bin.install_symlink "mongo" => "mongork"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongork/releases/download/v0.0.3-beta.7/mongork_Linux_arm64.tar.gz"
      sha256 "45db08eb71be85c119a455675ca0fd92d1f8ff402afff2fb8d803002fe4b2319"
      define_method(:install) do
        bin.install "mongork" => "mongo"
        bin.install_symlink "mongo" => "mmo"
        bin.install_symlink "mongo" => "mt"
        bin.install_symlink "mongo" => "mmt"
        bin.install_symlink "mongo" => "mongork"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
  end

  test do
    system "#{bin}/mongo --version"
  end
end
